### ISSUE TITLE
The results of select() and call() function are different

### ISSUE THREAD

**Issue by nodermann** [igorcoding/asynctnt#12]
Test space:
```lua
box.cfg{}
box.schema.create_space('test', { if_not_exists = true })
box.space.test:create_index('primary', { type = 'TREE', unique = true, if_not_exists = true })

-- function to search for multiple keys
function find(space, keys)
    local result = {}
    for i, key in pairs(keys) do
        result[i] = box.space[space]:select({key})[1]
    end
    return result
end
```
Tarantool prints the same results:
```bash
localhost:3301> box.space.test:select()
---
- - [20]
  - [42]
...

localhost:3301> find('test', {20,42})
---
- - [20]
  - [42]
...
```
Python test code snippet:
```python
import asyncio
import asynctnt

loop = asyncio.get_event_loop()
tnt_conn = asynctnt.Connection()


async def tasks():
    if not tnt_conn.is_connected:
        await tnt_conn.connect()
    await tnt_conn.insert('test', [20], replace=True)
    await tnt_conn.insert('test', [42], replace=True)
    result_1 = await tnt_conn.select('test')
    print('result_1', result_1)
    result_2 = await tnt_conn.call('find', ['test', [20, 42]])
    print('result_2', result_2)


loop.run_until_complete(tasks())
```

asynctnt prints different results:
```python
result_1 <Response sync=6 rowcount=2 data=[<TarantoolTuple 0=20>, <TarantoolTuple 0=42>]>
result_2 <Response sync=7 rowcount=1 data=[[[20], [42]]]>
```

**Comment by igorcoding** [comment]
Hello. This is just how Tarantool underlying protocol works.
What you see in the CALL is that Tarantool wraps everything you return from a function into a tuple, so it would be possible to make a multi value return, like this:
```
function f()
    return 1, 2, 3
end
```

The results from function above will arrive to python as an array [1, 2, 3].
So essentially result_2 means "array of return results, containing 1 array, containing 2 tuples [20] and [42]"
The difference of return types (TarantoolTuple vs list) comes from the difference in representing tuples. When you perform a SELECT request asynctnt knows what space you are selecting from, so it wraps results to TarantoolTuple which can be used either as a list or as a dict (just like in Tarantool itself).
But when you use CALL asynctnt can make no assumptions about data nature and its structure, so it returns data as is.

So, in a few words, it is impossible to deduce anything from a CALL on a connector side.
What you see in Tarantool REPL is just an `unpack()` of everything returned from a function and it does not look like an array.

**Comment by nodermann** [comment]
Ok, that makes sense, thank you. I added unpack() function:
```lua
function find(space, keys)
    local result = {}
    for i, key in pairs(keys) do
        result[i] = box.space[space]:select({key})[1]
    end
    return unpack(result)
end
```
Now all is well:
```bash
result_2 <Response sync=7 rowcount=2 data=[[20], [42]]>
```

**Comment by igorcoding** [comment]
Is everything clear, can I close the issue?
