### ISSUE TITLE
Add suport for Python 3.12

### ISSUE THREAD

**Issue by VladimirIsakov91** [igorcoding/asynctnt#31]
Running `pip install asynctnt ` for python 3.12 results in the following error: \
      gcc -pthread -B /home/user/anaconda3/envs/broken/compiler_compat -fno-strict-overflow -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/user/anaconda3/envs/broken/include -fPIC -O2 -isystem /home/user/anaconda3/envs/broken/include -fPIC -Ithird_party -Iasynctnt/iproto -I/home/user/anaconda3/envs/broken/include/python3.12 -c asynctnt/iproto/protocol.c -o build/temp.linux-x86_64-cpython-312/asynctnt/iproto/protocol.o
      asynctnt/iproto/protocol.c: In function ‘__pyx_f_8asynctnt_6iproto_8protocol_11SchemaSpace_get_index’:
      asynctnt/iproto/protocol.c:7361:7: warning: ‘ma_version_tag’ is deprecated [-Wdeprecated-declarations]
       7361 |       __Pyx_GetModuleGlobalName(__pyx_t_3, __pyx_n_s_logger); if (unlikely(!__pyx_t_3)) __PYX_ERR(1, 111, __pyx_L1_error)
            |       ^~~~~~~~~~~~~~~~~~~~~~~~~
      In file included from /home/user/anaconda3/envs/broken/include/python3.12/dictobject.h:90,
                       from /home/user/anaconda3/envs/broken/include/python3.12/Python.h:61,
                       from asynctnt/iproto/protocol.c:30:
      /home/user/anaconda3/envs/broken/include/python3.12/cpython/dictobject.h:22:34: note: declared here
         22 |     Py_DEPRECATED(3.12) uint64_t ma_version_tag;
            |                                  ^~~~~~~~~~~~~~
      asynctnt/iproto/protocol.c:7522:7: warning: ‘ma_version_tag’ is deprecated [-Wdeprecated-declarations]
       7522 |       __Pyx_GetModuleGlobalName(__pyx_t_4, __pyx_n_s_TarantoolSchemaError); if (unlikely(!__pyx_t_4)) __PYX_ERR(1, 122, __pyx_L1_error)
            |       ^~~~~~~~~~~~~~~~~~~~~~~~~
      In file included from /home/user/anaconda3/envs/broken/include/python3.12/dictobject.h:90,
                       from /home/user/anaconda3/envs/broken/include/python3.12/Python.h:61,
                       from asynctnt/iproto/protocol.c:30:
      /home/user/anaconda3/envs/broken/include/python3.12/cpython/dictobject.h:22:34: note: declared here
         22 |     Py_DEPRECATED(3.12) uint64_t ma_version_tag;
            |                                  ^~~~~~~~~~~~~~
      asynctnt/iproto/protocol.c: In function ‘__pyx_f_8asynctnt_6iproto_8protocol_6Schema_get_or_create_space’:
      asynctnt/iproto/protocol.c:8584:7: warning: ‘ma_version_tag’ is deprecated [-Wdeprecated-declarations]
       8584 |       __Pyx_GetModuleGlobalName(__pyx_t_3, __pyx_n_s_TarantoolSchemaError); if (unlikely(!__pyx_t_3)) __PYX_ERR(1, 160, __pyx_L1_error)
            |       ^~~~~~~~~~~~~~~~~~~~~~~~~
      In file included from /home/user/anaconda3/envs/broken/include/python3.12/dictobject.h:90,
                       from /home/user/anaconda3/envs/broken/include/python3.12/Python.h:61,
                       from asynctnt/iproto/protocol.c:30:
      /home/user/anaconda3/envs/broken/include/python3.12/cpython/dictobject.h:22:34: note: declared here
         22 |     Py_DEPRECATED(3.12) uint64_t ma_version_tag;
            |                                  ^~~~~~~~~~~~~~
      asynctnt/iproto/protocol.c: In function ‘__pyx_f_8asynctnt_6iproto_8protocol_6Schema_create_dummy_space’:
      asynctnt/iproto/protocol.c:8731:3: warning: ‘ma_version_tag’ is deprecated [-Wdeprecated-declarations]
       8731 |   __Pyx_GetModuleGlobalName(__pyx_t_2, __pyx_n_s_logger); if (unlikely(!__pyx_t_2)) __PYX_ERR(1, 169, __pyx_L1_error)
            |   ^~~~~~~~~~~~~~~~~~~~~~~~~
      In file included from /home/user/anaconda3/envs/broken/include/python3.12/dictobject.h:90,
                       from /home/user/anaconda3/envs/broken/include/python3.12/Python.h:61,
                       from asynctnt/iproto/protocol.c:30:
      /home/user/anaconda3/envs/broken/include/python3.12/cpython/dictobject.h:22:34: note: declared here
         22 |     Py_DEPRECATED(3.12) uint64_t ma_version_tag;
            |                                  ^~~~~~~~~~~~~~
      asynctnt/iproto/protocol.c: In function ‘__pyx_f_8asynctnt_6iproto_8protocol_6Schema_parse_space’:
      asynctnt/iproto/protocol.c:8969:3: warning: ‘Py_OptimizeFlag’ is deprecated [-Wdeprecated-declarations]
       8969 |   if (unlikely(!Py_OptimizeFlag)) {
            |   ^~
      ...
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for asynctnt
  Running setup.py clean for asynctnt
Failed to build asynctnt

**Comment by igorcoding** [comment]
Hi! Yeah sorry, for some reason the branch with Python 3.12 and PyPy support hadn't been merged. Now Python 3.12 wheels are published in the pypi under the version `asynctnt==2.1.0`.
